config/routes.rb
Rails.application.routes.draw do
  root 'neighborhoods#index'


  resources :reviews, only: [] do
      resources :votes, only: [:create, :update, :destroy]
  end

  resources :neighborhoods, only: [:index, :new, :create, :show, :update, :search] do
    resources :reviews, only: [:new, :create]
  end

  devise_for :users


  namespace :admin do
    resources :users, only: [:index, :update, :destroy, :edit]
  end

  namespace :admin do
    resources :neighborhoods, only: [:index, :update, :destroy]
  end

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  validates :name, presence: true

  def average_rating
    average = reviews.average(:rating) || 0
    average.round(2)
  end

  def self.search(search)
    query = "%#{search}%"

    if search
      where('name ILIKE :name OR description ILIKE :description', name: query, description: query)
    else
      all
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :neighborhood
  has_many :votes

  validates :description, presence: true
  validates :rating, inclusion: { in: 1..10 }
  validates :user_id, presence: true
  validates :neighborhood_id, presence: true

  def vote_from(user)
    votes.find_by(user_id: user.id)
  end

  def has_vote_from?(user)
    votes.find_by(user_id: user.id).present?
  end

  def upvotes
    votes.sum(:weight)
  end

  def update_total_upvotes
    self.upvotes = votes.sum(:weight)
    save
  end
end

app/models/search.rb
class Search < ActiveRecord::Base

  extend Textacular

  belongs_to :searchable, :polymorphic => true

  def self.new(query)
    query = query.to_s
    return [] if query.empty?
    self.search(query).map(&:searchable)
  end


  def readonly?
   true
  end

  def hash
    [searchable_id, searchable_type].hash
  end

  def eql?(result)
    searchable_id == result.searchable_id and
    searchable_type == result.searchable_type
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :neighborhoods
  has_many :reviews
  has_many :votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  def admin?
    role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :user, presence: true
  validates :review, presence: true
  validates :weight, inclusion: { in: [1, -1] }

  after_save :update_review_upvotes

  def upvote?
    weight == 1
  end

  def downvote?
    weight == -1
  end

  private

  def update_review_upvotes
    self.review.update_total_upvotes
  end
end

app/controllers/admin/neighborhoods_controller.rb
class Admin::NeighborhoodsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @neighborhoods = Neighborhood.where(approved: false).
    order(created_at: :desc)
  end

  def update
    @neighborhood = Neighborhood.find(params[:id])
    if params[:approved]
      @neighborhood.approved = true
      if @neighborhood.save
        flash[:notice] = "Neighborhood has been approved"
        NeighborhoodMailer.neighborhood_approved_email(@neighborhood).deliver
      else
        flash[:alert] = "Neighborhood could not be approved"
      end
    else
      flash[:alert] = "Neighborhood was declined"
    end
    redirect_to admin_neighborhoods_path
  end

  def destroy
    @neighborhood = Neighborhood.find(params[:id])
    @neighborhood.destroy
    flash[:alert] = "Neighborhood was rejected"
    redirect_to admin_neighborhoods_path
    NeighborhoodMailer.neighborhood_declined_email(@neighborhood).deliver
  end

  private
  def hood
    @neighborhood = Neighborhood.find(params[:id])
  end

  def authenticate_admin!
    unless current_user.role == "admin"
      flash[:alert] = "You are not authorized to view this page."
      redirect_to root_url
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @members = User.where(role: :member)
    @admins = User.where(role: :admin)
  end

  def update
    @member = User.find(params[:id])
    @member.role = 'admin'
    @member.save
    if @member.role == 'admin'
      flash[:notice] = 'User has been promoted'
      redirect_to admin_users_path
    else
      flash.now[:notice] = 'Something went wrong.'
      render 'admin/users'
    end
  end

  def destroy
    @member = User.find(params[:id])
    if @member
      @member.destroy
      flash[:notice] = 'User has been deleted'
      redirect_to admin_users_path
    else
      flash.now[:notice] = 'Something went wrong.'
      render 'admin/users'
    end
  end

  private

  def authenticate_admin!
    unless current_user.role == 'admin'
      flash[:alert] = 'You are not authorized to view this page.'
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def admin?
    current_user.role == 'admin'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    if params[:q].present?
      @results = Search.new(params[:q])
      @neighborhoods = @results.map do |result|
        if result.class == Review
          result.neighborhood
        else
          result
        end
      end
      @neighborhoods.uniq!

      @neighborhoods = Kaminari.paginate_array(@neighborhoods).page(params[:page]).per(10)
    else
      @neighborhoods = Neighborhood.all.page(params[:page])
    end
  end

  def new
    @neighborhood = Neighborhood.new
  end

  def create
    @neighborhood = current_user.neighborhoods.build(neighborhood_params)

    if @neighborhood.save
      NeighborhoodMailer.new_neighborhood_email(@neighborhood).deliver
      flash[:notice] = "Success! Your neighborhood is pending approval."
      redirect_to neighborhood_path(@neighborhood)
    else
      flash[:alert] = "Could not save."
      render :new
    end
  end

  def show
    @neighborhood = Neighborhood.find(params[:id])
    @reviews = @neighborhood.reviews.order(upvotes: :desc)
    if !current_user
      flash[:alert] = 'Please sign in to vote on reviews.'
    end
  end

  private

  def neighborhood_params
    params.require(:neighborhood).permit(:name, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @review = Review.new
  end

  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @review = @neighborhood.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      flash[:notice] = 'Successfully added.'
      NeighborhoodMailer.neighborhood_review_email(@neighborhood).deliver
      redirect_to neighborhood_path(@review.neighborhood)
    else
      flash[:alert] = 'Could not save.'
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    vote = Vote.create(
      user: current_user, review_id: params[:review_id])
    vote.weight = params[:weight]
    if vote.save
      flash[:notice] = 'Success! Your vote has been counted.'
    else
      flash[:alert] = 'Could not save your vote.'
    end
    redirect_to neighborhood_path(vote.review.neighborhood)
  end

  def update
    vote = Vote.find_by(
      user: current_user, review_id: params[:review_id])
    vote.weight = params[:weight]
    if vote.save
      flash[:notice] = 'Success! Your vote has been counted.'
    else
      flash[:alert] = 'Could not save your vote.'
    end
    redirect_to neighborhood_path(vote.review.neighborhood)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class
    if flash[:notice]
      "alert alert-success"
    else
      "alert alert-danger"
    end
  end
end

app/views/admin/neighborhoods/index.html.erb
<div class="container">
  <h1>Neighborhood Dashboard</h1>
  <div class="neighborhood_table">
    <table class="table table-striped">
      <tr>
        <th>Neighborhood</th>
        <th>User</th>
        <th>Approve</th>
        <th>Delete</th>
      </tr>
      <% @neighborhoods.each do |hood| %>
      <tr>
        <td><%= hood.name %></td>
        <td><%= hood.user.email %></td>
        <td><%= button_to "Approve", admin_neighborhood_path(hood, approved: true), method: :put %></td>
        <td><%= button_to "Delete", admin_neighborhood_path(hood), method: :delete %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1>Edit Users - Admin Page</h1>
  <em>These actions cannot be undone</em>

<h2>Members</h2>
<table>
  <% if !@members.any? %>
      <em>Currently no non-admin members</em>
  <% end %>
  <% @members.each do |member| %>
  <tr>
    <td>
      <%= member.email %> -
      <%= link_to 'Delete', admin_user_path(member), data: { confirm: "This action will permanently delete this user record. Are you sure?" }, method: :delete %> |
      <%= link_to 'Promote', admin_user_path(member), data: { confirm: "Promotions are permanent. Are you sure?" }, method: :patch %>
    </td>
  </tr>
  <% end %>
</table>
<h2>Admins</h2>
<table>
  <% @admins.each do |admin| %>
  <tr>
    <td>
      <%= admin.email %>
    </td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neighborhoods</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Neighborhoods</a>
      </div>
      <div class="navbar-collapse collapse">

        <%= form_tag(neighborhoods_path, { method: "get", class: "navbar-form navbar-right"}) do %>
          <%= text_field_tag :q, params[:q], placeholder: "Find Neighborhoods", class: "form-control"  %>
          <%= submit_tag("Search", class: "form-control") %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
            <li>
              <%= image_tag current_user.avatar.url, class: "img-circle" %>
            </li>
            <li>
              <%= link_to("Signed in as #{current_user.email} (Sign out?)", destroy_user_session_path, method: :delete) %>
            </li>
            <li>
              <%= link_to('Edit Profile', edit_user_registration_path, data: {toggle: "modal", target: '#edit-profilemodal', remote: 'false'})  %>
            </li>
            <li>
              <%= link_to('Recommend Neighborhood', new_neighborhood_path, data: {toggle: 'modal', target:
                '#new-neighborhood', remote: 'false'})   %>
            </li>
              <% if current_user.admin? %>
                <li><%= link_to('Edit Users', admin_users_path) %></li>
                <li><%= link_to('Pending Neighborhoods', edit_user_registration_path) %></li>
              <% end %>
          <% else %>
            <li>
              <%= link_to('Sign in', "#", data: {toggle: "modal", target: '#signinmodal'})  %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!-- end of nav bar -->
  <% flash.each do |key, value| %>
    <div class="<%= flash_class %>">
      <%= value %>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

<% if user_signed_in? %>
  <!-- Add neighborhood Modal -->
  <!-- Button trigger modal -->
  <div class="modal fade" id="new-neighborhood" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a New Neighborhood</h4>
        </div>
        <div class="modal-body">
          <div class="border-form-div">
            <%= simple_form_for(Neighborhood.new) do |f| %>
              <%= f.input :name %>
              <%= f.input :description  %>
              <%= f.button :submit, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end of add neighborhood modal -->
<% end %>
<!-- Sign In Modal -->
<!-- Button trigger modal -->
<div class="modal fade" id="signinmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign in</h4>
      </div>
      <div class="modal-body">
        <div class="border-form-div">
          <%= form_for(User.new, url: user_session_path) do |f| %>
            <%= f.email_field :email, :autofocus => true, :placeholder => 'Email' %>
            <%= f.password_field :password, :placeholder => 'Password'  %>
            <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
            <%= f.submit "Sign in", class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end of sign in modal -->


  <!-- Edit profile Modal -->
<% if user_signed_in? %>
  <!-- Button trigger modal -->
  <div class="modal fade" id="edit-profilemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit Profile</h4>
        </div>
        <div class="modal-body">
          <div class="border-form-div">

          <%= form_for(current_user, url: user_registration_path, method: :put ) do |f| %>

            <div><%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %></div>

            <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
              <%= f.password_field :password, autocomplete: "off" %></div>

            <div><%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

            <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
              <%= f.password_field :current_password, autocomplete: "off" %></div>

            <div>
              Add an avatar
              <%=f.file_field :avatar %><br>
            </div>

            <div><%= f.submit "Update", class: 'btn btn-primary' %></div>
          <% end %>

          <h3>Cancel my account</h3>

          <p>Unhappy? <%= button_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete,:class=>'btn btn-primary'%></p>

          <%= link_to "Back", :back %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<!-- end of edit profile modal -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

</body>
</html>

app/views/neighborhoods/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Neighborhoods</h1>
    <p class="lead">Find, rate, review spots in Boston </p>
    <% if !user_signed_in? %>
      <p><a class="btn btn-lg btn-success" href= "/users/sign_up" role="button">Sign up!</a></p>
    <% end %>
  </div>
  <div class="row neighborhood_home">
    <% if @neighborhoods.any? %>
      <% @neighborhoods.each do |neighborhood| %>
        <div class="col-lg-4">
          <div class="homepage_hood"><h4><%= neighborhood.name %></h4><div class="rating"><%= neighborhood.average_rating %></div>
        <%=link_to "Read the reviews!", neighborhood %></div>
        </div>
      <% end %>
    <% else %>
      <h4>Oops, we couldn't find anything for "<%= params[:q] %>." Please search again.</h4>
    <% end %>
  </div>
  <%= paginate @neighborhoods %>
</div> <!-- /container -->

app/views/neighborhoods/new.html.erb
<h2>Add a New Neighborhood</h2>

<div class="border-form-div">
<%= simple_form_for(@neighborhood) do |f| %>
  <%= f.input :name %>
  <%= f.input :description  %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/neighborhoods/show.html.erb
<div class="neighborhood_title">
  <%= @neighborhood.name %>
</div>

<div class="neighborhood_detail">
  <%= @neighborhood.description %>
</div>
  <h2>Average Rating: <%= @neighborhood.average_rating %></h2>
  <h2><%= link_to "Add Review", "/neighborhoods/#{params[:id]}/reviews/new" %></h2>

<% @reviews.each do |review| %>
  <table class="table">
    <td>
      <%= review.upvotes %>
    </td>
      <% if current_user %>
      <% vote = review.vote_from(current_user) %>

      <% if vote.present? %>
      <% if vote.downvote? %>
    <td>
      <button type="button">
       <%=link_to"",review_vote_path(review, vote, weight: 1),
          method: :put, class: "glyphicon glyphicon-arrow-up"%>
      </button>
    </td>
      <% end %>
      <% if vote.upvote? %>
    <td>
      <button type="button">
       <%=link_to"",review_vote_path(review, vote, weight: -1),
          method: :put, class: "glyphicon glyphicon-arrow-down"%>
      </button>
    </td>
      <% end %>
      <% else %>
    <td>
      <%= button_to 'Upvote', review_votes_path(review, weight: 1)%>
      <%= button_to 'Downvote', review_votes_path(review, weight: -1)%>
    </td>
      <% end %>
      <% end %>
    <td>
      <%= review.description %>
    </td>
    <td>
      written by <%= review.user.email %>
    </td>
  </table>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a Review for <%=@neighborhood.name%></h1>

<div class="dogface">
  <%= simple_form_for [@neighborhood, @review] do |f| %>
    <%= f.input :description %>
    <%= f.input :rating, collection: 1..10 %><br>
    <%= f.button :submit , class: 'btn btn-primary' %>
  <% end %>
</div>